services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      default:
        ipv4_address: ${TUNNEL_IP_ADDRESS}

  proxy:
    image: nginx:1.26.2
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - PROXY_IP_ADDRESS=${PROXY_IP_ADDRESS}
      - RESOLVER_IP_ADDRESS=${RESOLVER_IP_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        ipv4_address: ${PROXY_IP_ADDRESS}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
